### ISSUE TITLE
[Bug]: Ingest job failure during 1x load test 7-11-2022

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#154]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Noticed failures of: "raise CooperationNotPossibleException( osaka.utils.CooperationNotPossibleException: No source specified. Cooperation not possible for s3://...products/HLS.L30.T17ULV.2022023T163751.v2.0.B07/_publish.context.json"

Rishi noted [54 of these](https://100.104.40.10/hysds_ui/figaro?resource=%22job%22&status=%22job-failed%22&short_error=%22No+source+specified......ntext.json%22) during the July 11th 1X load test

These files did indeed not exist in the rs S3 bucket.

```
Traceback (most recent call last):
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 38, in __enter__
self.dlock.lock(lockMetadata)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/lock.py", line 78, in lock
raise osaka.utils.OsakaException("Lock file already locked")
osaka.utils.OsakaException: Lock file already locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1412, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 692, in publish_datasets
prod_json = publish_dataset(prod_dir, dataset_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 595, in publish_dataset
metrics, prod_json = get_func("hysds.dataset_ingest.ingest")(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 434, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 193, in publish_dataset
osaka.main.put(publ_ctx_file, publ_ctx_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 104, in transfer
with osaka.cooperator.Cooperator(source, dlock, lockMetadata) as coop:
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 43, in __enter__
self.whenLocked()
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 70, in whenLocked
raise CooperationNotPossibleException(
osaka.utils.CooperationNotPossibleException: No source specified. Cooperation not possible for s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd-pyoon/products/HLS.L30.T34KBU.2022023T084521.v2.0.B02/_publish.context.json
```

### What did you expect?

Expected no errors

### Reproducible steps

```bash
It's unclear if these errors are reproducible and to what extent. We will have to run the test again and see.
```

### Environment

```bash
pcm_branch    = "1.0.0-rc.1.0"
hysds_release = "v4.0.1-beta.8-oraclelinux"
Phil's personal dev cluster
```

**Comment by hhlee445** [comment]
Won't fix this issue due to simplified the pipeline.
