### ISSUE TITLE
[Bug]: Failures with INGEST_STAGED jobs  during load test

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#167]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When we performed few load tests, there were many failures with INGEST_STAGED jobs.

Here are few common errors captured.
1. Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 193, in publish_dataset
osaka.main.put(publ_ctx_file, publ_ctx_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 87, in transfer
raise osaka.utils.NoClobberException(error)
osaka.utils.NoClobberException: Destination, s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.S30.T36QUE.2022025T082231.v2.0.B12/_publish.context.json, already exists and no-clobber is set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 434, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 195, in publish_dataset
raise NoClobberPublishContextException(
hysds.dataset_ingest.NoClobberPublishContextException: Failed to clobber s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.S30.T36QUE.2022025T082231.v2.0.B12/_publish.context.json when noclobber is True.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1412, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 692, in publish_datasets
prod_json = publish_dataset(prod_dir, dataset_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 595, in publish_dataset
metrics, prod_json = get_func("hysds.dataset_ingest.ingest")(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 540, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 206, in publish_dataset
osaka.main.put(abs_path, dest_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 87, in transfer
raise osaka.utils.NoClobberException(error)
osaka.utils.NoClobberException: Destination, s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.S30.T36QUE.2022025T082231.v2.0.B12/HLS.S30.T36QUE.2022025T082231.v2.0.B12.met.json.md5, already exists and no-clobber is set

2. Traceback (most recent call last):
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 38, in __enter__
self.dlock.lock(lockMetadata)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/lock.py", line 78, in lock
raise osaka.utils.OsakaException("Lock file already locked")
osaka.utils.OsakaException: Lock file already locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1412, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 692, in publish_datasets
prod_json = publish_dataset(prod_dir, dataset_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 595, in publish_dataset
metrics, prod_json = get_func("hysds.dataset_ingest.ingest")(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 434, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 206, in publish_dataset
osaka.main.put(abs_path, dest_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 104, in transfer
with osaka.cooperator.Cooperator(source, dlock, lockMetadata) as coop:
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 43, in __enter__
self.whenLocked()
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 66, in whenLocked
ex_source = self.dlock.getLockMetadata("source")
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/lock.py", line 102, in getLockMetadata
filelike = handle.get(self.luri)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/storage/s3.py", line 152, in get
obj.download_fileobj(fh)
File "/home/ops/verdi/lib/python3.9/site-packages/boto3/s3/inject.py", line 759, in object_download_fileobj
return self.meta.client.download_fileobj(
File "/home/ops/verdi/lib/python3.9/site-packages/boto3/s3/inject.py", line 679, in download_fileobj
return future.result()
File "/home/ops/verdi/lib/python3.9/site-packages/s3transfer/futures.py", line 103, in result
return self._coordinator.result()
File "/home/ops/verdi/lib/python3.9/site-packages/s3transfer/futures.py", line 266, in result
raise self._exception
File "/home/ops/verdi/lib/python3.9/site-packages/s3transfer/tasks.py", line 139, in __call__
return self._execute_main(kwargs)
File "/home/ops/verdi/lib/python3.9/site-packages/s3transfer/tasks.py", line 162, in _execute_main
return_value = self._main(**kwargs)
File "/home/ops/verdi/lib/python3.9/site-packages/s3transfer/download.py", line 569, in _main
response = client.get_object(
File "/home/ops/verdi/lib/python3.9/site-packages/botocore/client.py", line 391, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/home/ops/verdi/lib/python3.9/site-packages/botocore/client.py", line 719, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

3. Traceback (most recent call last):
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 38, in __enter__
self.dlock.lock(lockMetadata)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/lock.py", line 78, in lock
raise osaka.utils.OsakaException("Lock file already locked")
osaka.utils.OsakaException: Lock file already locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1412, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 692, in publish_datasets
prod_json = publish_dataset(prod_dir, dataset_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 595, in publish_dataset
metrics, prod_json = get_func("hysds.dataset_ingest.ingest")(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 434, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 193, in publish_dataset
osaka.main.put(publ_ctx_file, publ_ctx_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 104, in transfer
with osaka.cooperator.Cooperator(source, dlock, lockMetadata) as coop:
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 43, in __enter__
self.whenLocked()
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 74, in whenLocked
raise CooperationNotPossibleException(
osaka.utils.CooperationNotPossibleException: /data/work/jobs/2022/07/28/21/23/ingest-staged-HLS.S30.T34JDL.2022025T082231.v2.0.B11.tif-20220728T210017.689691Z/.pub_contextzv_jor72/_publish.context.json differs incoming source /data/work/jobs/2022/07/28/21/23/ingest-staged-HLS.S30.T34JDL.2022025T082231.v2.0.B11.tif-20220728T210017.716229Z/.pub_contextzo7dkr8s/_publish.context.json. Cooperation not possible for s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.S30.T34JDL.2022025T082231.v2.0.B11/_publish.context.json

4. Traceback (most recent call last):
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 38, in __enter__
self.dlock.lock(lockMetadata)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/lock.py", line 78, in lock
raise osaka.utils.OsakaException("Lock file already locked")
osaka.utils.OsakaException: Lock file already locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1412, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 692, in publish_datasets
prod_json = publish_dataset(prod_dir, dataset_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 595, in publish_dataset
metrics, prod_json = get_func("hysds.dataset_ingest.ingest")(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 434, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 193, in publish_dataset
osaka.main.put(publ_ctx_file, publ_ctx_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 104, in transfer
with osaka.cooperator.Cooperator(source, dlock, lockMetadata) as coop:
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 43, in __enter__
self.whenLocked()
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 70, in whenLocked
raise CooperationNotPossibleException(
osaka.utils.CooperationNotPossibleException: No source specified. Cooperation not possible for s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.L30.T36RWR.2022025T081814.v2.0.B05/_publish.context.json

5. Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 193, in publish_dataset
osaka.main.put(publ_ctx_file, publ_ctx_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 87, in transfer
raise osaka.utils.NoClobberException(error)
osaka.utils.NoClobberException: Destination, s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.S30.T37SBV.2022025T082231.v2.0.B11/_publish.context.json, already exists and no-clobber is set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 434, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 195, in publish_dataset
raise NoClobberPublishContextException(
hysds.dataset_ingest.NoClobberPublishContextException: Failed to clobber s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.S30.T37SBV.2022025T082231.v2.0.B11/_publish.context.json when noclobber is True.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1412, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 692, in publish_datasets
prod_json = publish_dataset(prod_dir, dataset_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 595, in publish_dataset
metrics, prod_json = get_func("hysds.dataset_ingest.ingest")(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 448, in ingest
osaka.main.get(publ_ctx_url, orig_publ_ctx_file, params=osaka_params)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 76, in get
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 106, in transfer
metrics = self.transfer_uri(source, shandle, dest, dhandle)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 157, in transfer_uri
counts = osaka.utils.product_composite_iterator(source, shandle, transfer_one)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/utils.py", line 105, in product_composite_iterator
return list(map(callback, uris))
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 152, in transfer_one
stream = shandle.get(uri)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/storage/s3.py", line 155, in get
raise osaka.utils.OsakaFileNotFound(
osaka.utils.OsakaFileNotFound: File s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.S30.T37SBV.2022025T082231.v2.0.B11/_publish.context.json doesn't exist.

6. Traceback (most recent call last):
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 38, in __enter__
self.dlock.lock(lockMetadata)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/lock.py", line 78, in lock
raise osaka.utils.OsakaException("Lock file already locked")
osaka.utils.OsakaException: Lock file already locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1412, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 692, in publish_datasets
prod_json = publish_dataset(prod_dir, dataset_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/utils.py", line 595, in publish_dataset
metrics, prod_json = get_func("hysds.dataset_ingest.ingest")(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 434, in ingest
publish_dataset(
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/dataset_ingest.py", line 206, in publish_dataset
osaka.main.put(abs_path, dest_url, params=params, noclobber=True)
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 38, in put
transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/main.py", line 118, in transfer
transfer.transfer(
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 128, in transfer
raise err
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/transfer.py", line 104, in transfer
with osaka.cooperator.Cooperator(source, dlock, lockMetadata) as coop:
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 43, in __enter__
self.whenLocked()
File "/home/ops/verdi/ops/osaka-1.1.0/osaka/cooperator.py", line 74, in whenLocked
raise CooperationNotPossibleException(
osaka.utils.CooperationNotPossibleException: /data/work/jobs/2022/07/28/21/17/ingest-staged-HLS.L30.T35PRN.2022025T082301.v2.0.B02.tif-20220728T205833.247175Z/output/HLS.L30.T35PRN.2022025T082301.v2.0.B02/HLS.L30.T35PRN.2022025T082301.v2.0.B02.tif differs incoming source /data/work/jobs/2022/07/28/21/17/ingest-staged-HLS.L30.T35PRN.2022025T082301.v2.0.B02.tif-20220728T205833.211162Z/output/HLS.L30.T35PRN.2022025T082301.v2.0.B02/HLS.L30.T35PRN.2022025T082301.v2.0.B02.tif. Cooperation not possible for s3://s3-us-west-2.amazonaws.com:80/opera-dev-rs-fwd/products/HLS.L30.T35PRN.2022025T082301.v2.0.B02/HLS.L30.T35PRN.2022025T082301.v2.0.B02.tif

### What did you expect?

When there was duplicate ingest jobs, I expected one job executed successfully and one job would marked as deduped and not executed at all.

Gerald recommended to update ISL lambda function to set 'payload_hash' parameter using s3.object.eTag value.

### Environment

```bash
- PCM 1.0.0-rc.2.0
- dev-common cluster
```

**Comment by hhlee445** [comment]
Modified ISL lambda function to set 'payload_hash' with s3.object.eTag value and delivered https://github.com/nasa/opera-sds-lambdas/commit/d309c4f0448dc43acd3a3c80c2eaad5d2fabd266
