### ISSUE TITLE
[Bug]: CSLC and RTC SCIFLO failure - ran out of space

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#414]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Ran end-to-end testing of R2 and there was one SCIFLO job failure with out-of-space disk error.

A few days later a large set of data was run on the PST cluster and we observed hundreds of same failures w the following exception:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/job_worker.py", line 1410, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/triage.py", line 138, in triage
prod_json = publish_dataset(triage_dir, ds_file, job, ctx)
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/dataset_ingest.py", line 202, in publish_dataset
shutil.copy(context_file, prod_context_file)
File "/opt/conda/lib/python3.9/shutil.py", line 427, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/opt/conda/lib/python3.9/shutil.py", line 266, in copyfile
with open(dst, 'wb') as fdst:
OSError: [Errno 28] No space left on device: '/data/work/jobs/2023/03/08/23/03/SCIFLO_L2_CSLC_S1__2.0.0-rc.3.0-S1B_IW_SLC__1SDV_20200101T013924_20200101T013954_019617_025131_20F8-20230308T221045.929422Z/triaged_job-SCIFLO_L2_CSLC_S1__2.0.0-rc.3.0-S1B_IW_SLC__1SDV_20200101T013924_20200101T013954_019617_025131_20F8-20230308T221045.929422Z_task-23bede8a-fccc-414a-9bd8-62d1e580688b/triaged_job-SCIFLO_L2_CSLC_S1__2.0.0-rc.3.0-S1B_IW_SLC__1SDV_20200101T013924_20200101T013954_019617_025131_20F8-20230308T221045.929422Z_task-23bede8a-fccc-414a-9bd8-62d1e580688b.context.json'

The solution likely is to alter the job-spec file for the CSLC and RTC PGE jobs so that the system clears out the jobs folder more aggressively - there's no point in keeping old job files around.

On a fresh PGE EC2 we do not run out of space because there's no data from previous runs present:
![image](https://user-images.githubusercontent.com/104090313/224781291-322fb955-2d7b-4308-919b-171b0359e043.png)

You can see here that an EC that's been running for a while is still carrying job data from previous runs. It will likely run out of space during this or the next run:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/104090313/224779341-bc6aef02-6ca2-410e-8889-04c0fb3dafa1.png">

<img width="394" alt="image" src="https://user-images.githubusercontent.com/104090313/224779733-3c99d11f-e7fc-4ed8-81d6-b5d213f20dc5.png">

### What did you expect?

Expected the SCIFLO jobs to complete without errors.

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by philipjyoon** [comment]
The SCIFLO job that had failed previously but completed the second time (after a brand new EC2 had spun up) used 47GB of job data:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/104090313/224786165-c912f505-5386-4acf-9729-9784570d9ff1.png">

**Comment by hhlee445** [comment]
We will need to clean out the workspace after the PGE job completes.

**Comment by philipjyoon** [comment]
Setting the job-spec disk_usage parameter to 70GB will likely resolve this issue.

**Comment by philipjyoon** [comment]
Was able to reproduce this issue by running two CSLC PGE jobs back to back w ASG max set to 1:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/104090313/224825856-866f0253-227d-479d-baa1-1941eface1ef.png">

**Comment by philipjyoon** [comment]
Changing the disk_usage parameter to 70Gb resolved this issue. Using rc4 tag ran e2e test with artificially low SCIFLO ASG max to force more cycles on the same EC2 instance. I observed as many as 6 cycles on the same EC2 and all ran without any errors. Watching disk usage I could see that the data was getting deleted actively.
