### ISSUE TITLE
SLC download error w R2 RC4 tag - NoQueryResultsException

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#426]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

python daac_data_subscriber.py query -c SENTINEL-1A_SLC --release-version=2.0.0-rc.4.0 --native-id=S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3-SLC --chunk-size=1 --job-queue=opera-job_worker-slc_data_download

This job errors will be added as comment below

### What did you expect?

I expected it to work

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by philipjyoon** [comment]
[2023-03-15 22:18:53,424: INFO/conf_util/__init__] file: /home/ops/verdi/ops/opera-pcm/conf/settings.yaml
[2023-03-15 22:18:53,445: INFO/root/run] Log level set to INFO
[2023-03-15 22:18:53,446: INFO/root/run] argv=['/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py', 'download', '-p', 'ASF', '--endpoint=OPS', '--batch-ids', 'S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip', '--start-date=1900-01-01T00:00:00Z', '--end-date=2023-03-15T22:14:14Z', '--transfer-protocol=auto']
[2023-03-15 22:18:53,446: INFO/root/run] job_path: <_io.TextIOWrapper name='_job.json' mode='r+' encoding='UTF-8'>
[2023-03-15 22:18:53,446: INFO/root/run] local_job_json={'command': {'arguments': ['--endpoint=OPS', '--batch-ids S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip', '--start-date=1900-01-01T00:00:00Z', '--end-date=2023-03-15T22:14:14Z', '', '', '', '--transfer-protocol=auto'], 'env': [], 'options': [], 'path': '/home/ops/verdi/ops/opera-pcm/data_subscriber/slc/slc_download.sh'}, 'container_image_name': 'container-nasa_opera-sds-pcm:2.0.0-rc.4.0', 'container_image_url': 's3://s3-us-west-2.amazonaws.com/opera-int-cc-pop1/container-nasa_opera-sds-pcm:2.0.0-rc.4.0.tar.gz', 'container_mappings': {'$HOME/.aws': '/home/ops/.aws', '$HOME/.netrc': '/home/ops/.netrc', '$HOME/verdi/etc/settings.yaml': '/home/ops/verdi/ops/opera-pcm/conf/settings.yaml'}, 'context': {'_command': "/home/ops/verdi/ops/opera-pcm/data_subscriber/slc/slc_download.sh '--endpoint=OPS' '--batch-ids S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip' '--start-date=1900-01-01T00:00:00Z' '--end-date=2023-03-15T22:14:14Z' '' '' '' '--transfer-protocol=auto'", '_disk_usage': '20GB', '_prov': {'wasGeneratedBy': 'task_id:40ef7c7a-c1ca-4412-b166-b9edefaf1481'}, 'batch_ids': '--batch-ids S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip', 'container_image_name': 'container-nasa_opera-sds-pcm:2.0.0-rc.4.0', 'container_image_url': 's3://s3-us-west-2.amazonaws.com/opera-int-cc-pop1/container-nasa_opera-sds-pcm:2.0.0-rc.4.0.tar.gz', 'container_mappings': {'$HOME/.aws': '/home/ops/.aws', '$HOME/.netrc': '/home/ops/.netrc', '$HOME/verdi/etc/settings.yaml': '/home/ops/verdi/ops/opera-pcm/conf/settings.yaml'}, 'container_specification': {'digest': 'sha256:6d9ebbedd05e44fde221aaba1563b73f9f08ee9375cfc9a458c0d5d685deb1f5', 'id': 'container-nasa_opera-sds-pcm:2.0.0-rc.4.0', 'url': 's3://s3-us-west-2.amazonaws.com/opera-int-cc-pop1/container-nasa_opera-sds-pcm:2.0.0-rc.4.0.tar.gz', 'version': '2.0.0-rc.4.0'}, 'dry_run': '', 'end_datetime': '--end-date=2023-03-15T22:14:14Z', 'endpoint': '--endpoint=OPS', 'job_priority': 0, 'job_specification': {'command': '/home/ops/verdi/ops/opera-pcm/data_subscriber/slc/slc_download.sh', 'container': 'container-nasa_opera-sds-pcm:2.0.0-rc.4.0', 'disk_usage': '20GB', 'id': 'job-slc_download:2.0.0-rc.4.0', 'imported_worker_files': {'$HOME/.aws': '/home/ops/.aws', '$HOME/.netrc': '/home/ops/.netrc', '$HOME/verdi/etc/settings.yaml': '/home/ops/verdi/ops/opera-pcm/conf/settings.yaml'}, 'job-version': '2.0.0-rc.4.0', 'params': [{'destination': 'positional', 'name': 'endpoint', 'value': '--endpoint=OPS'}, {'destination': 'positional', 'name': 'batch_ids', 'value': '--batch-ids S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip'}, {'destination': 'positional', 'name': 'start_datetime', 'value': '--start-date=1900-01-01T00:00:00Z'}, {'destination': 'positional', 'name': 'end_datetime', 'value': '--end-date=2023-03-15T22:14:14Z'}, {'destination': 'positional', 'name': 'smoke_run', 'value': ''}, {'destination': 'positional', 'name': 'dry_run', 'value': ''}, {'destination': 'positional', 'name': 'use_temporal', 'value': ''}, {'destination': 'positional', 'name': 'transfer_protocol', 'value': '--transfer-protocol=auto'}], 'post': ['hysds.triage.triage'], 'recommended-queues': ['opera-job_worker-slc_data_download'], 'resource': 'jobspec', 'soft_time_limit': 3600, 'time_limit': 3660}, 'localize_urls': [], 'runtime_options': {}, 'smoke_run': '', 'start_datetime': '--start-date=1900-01-01T00:00:00Z', 'tag': 'trigger-slc_download', 'transfer_protocol': '--transfer-protocol=auto', 'use_temporal': ''}, 'delivery_info': {'exchange': '', 'priority': 0, 'redelivered': False, 'routing_key': 'opera-job_worker-slc_data_download'}, 'job_id': 'job-WF-slc_download-20230315T221415.498875Z', 'job_info': {'context_file': '/data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/_context.json', 'datasets_cfg_file': '/home/ops/verdi/etc/datasets.json', 'dedup': True, 'execute_node': '100.104.49.116', 'facts': {'ec2_instance_id': 'i-083816e9e2133af6c', 'ec2_instance_type': 'c5n.2xlarge', 'ec2_placement_availability_zone': 'us-west-2b', 'fqdn': '100.104.49.116', 'hysds_execute_node': '100.104.49.116', 'hysds_public_ip': '100.104.49.116', 'ipaddress_eth0': '100.104.49.116', 'is_virtual': True, 'virtual': 'docker'}, 'id': 'job-WF-slc_download-20230315T221415.498875Z', 'job_dir': '/data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z', 'job_payload': {'job_type': 'job:job-slc_download:2.0.0-rc.4.0', 'payload_task_id': '9499d367-c0b0-4c2c-85e9-c3efc77f3b04'}, 'job_queue': 'opera-job_worker-slc_data_download', 'job_url': 'http://100.104.49.116:8085/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z', 'metrics': {'inputs_localized': [], 'job_dir_size': 0, 'products_staged': [], 'usage_stats': []}, 'payload_hash': '279964b340b241abb52f552a436bdbf0', 'public_ip': '100.104.49.116', 'soft_time_limit': 3600, 'time_limit': 3900, 'time_queued': '2023-03-15T22:14:15.498882Z'}, 'localize_urls': [], 'name': 'job-WF-slc_download-20230315T221415.498875Z', 'params': {'_command': "/home/ops/verdi/ops/opera-pcm/data_subscriber/slc/slc_download.sh '--endpoint=OPS' '--batch-ids S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip' '--start-date=1900-01-01T00:00:00Z' '--end-date=2023-03-15T22:14:14Z' '' '' '' '--transfer-protocol=auto'", '_disk_usage': '20GB', 'batch_ids': '--batch-ids S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip', 'container_specification': {'digest': 'sha256:6d9ebbedd05e44fde221aaba1563b73f9f08ee9375cfc9a458c0d5d685deb1f5', 'id': 'container-nasa_opera-sds-pcm:2.0.0-rc.4.0', 'url': 's3://s3-us-west-2.amazonaws.com/opera-int-cc-pop1/container-nasa_opera-sds-pcm:2.0.0-rc.4.0.tar.gz', 'version': '2.0.0-rc.4.0'}, 'dry_run': '', 'end_datetime': '--end-date=2023-03-15T22:14:14Z', 'endpoint': '--endpoint=OPS', 'job_specification': {'command': '/home/ops/verdi/ops/opera-pcm/data_subscriber/slc/slc_download.sh', 'container': 'container-nasa_opera-sds-pcm:2.0.0-rc.4.0', 'disk_usage': '20GB', 'id': 'job-slc_download:2.0.0-rc.4.0', 'imported_worker_files': {'$HOME/.aws': '/home/ops/.aws', '$HOME/.netrc': '/home/ops/.netrc', '$HOME/verdi/etc/settings.yaml': '/home/ops/verdi/ops/opera-pcm/conf/settings.yaml'}, 'job-version': '2.0.0-rc.4.0', 'params': [{'destination': 'positional', 'name': 'endpoint', 'value': '--endpoint=OPS'}, {'destination': 'positional', 'name': 'batch_ids', 'value': '--batch-ids S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip'}, {'destination': 'positional', 'name': 'start_datetime', 'value': '--start-date=1900-01-01T00:00:00Z'}, {'destination': 'positional', 'name': 'end_datetime', 'value': '--end-date=2023-03-15T22:14:14Z'}, {'destination': 'positional', 'name': 'smoke_run', 'value': ''}, {'destination': 'positional', 'name': 'dry_run', 'value': ''}, {'destination': 'positional', 'name': 'use_temporal', 'value': ''}, {'destination': 'positional', 'name': 'transfer_protocol', 'value': '--transfer-protocol=auto'}], 'post': ['hysds.triage.triage'], 'recommended-queues': ['opera-job_worker-slc_data_download'], 'resource': 'jobspec', 'soft_time_limit': 3600, 'time_limit': 3660}, 'localize_urls': [], 'smoke_run': '', 'start_datetime': '--start-date=1900-01-01T00:00:00Z', 'tag': 'trigger-slc_download', 'transfer_protocol': '--transfer-protocol=auto', 'use_temporal': ''}, 'priority': 0, 'runtime_options': {}, 'tag': 'trigger-slc_download', 'task_id': '40ef7c7a-c1ca-4412-b166-b9edefaf1481', 'type': 'job-slc_download:2.0.0-rc.4.0', 'username': 'hysdsops'}
[2023-03-15 22:18:53,446: INFO/root/run] job_id='9499d367-c0b0-4c2c-85e9-c3efc77f3b04'
[2023-03-15 22:18:53,446: INFO/root/run] args.subparser_name='download'
[2023-03-15 22:18:53,811: INFO/root/get_download_timerange] download_timerange=DateTimeRange(start_date='1900-01-01T00:00:00Z', end_date='2023-03-15T22:14:14Z')
[2023-03-15 22:18:53,816: INFO/elasticsearch/log_request_success] POST http://100.104.49.22:9200/slc_catalog/_search?size=1000 [status:200 request:0.005s]
[2023-03-15 22:18:53,818: INFO/elasticsearch/log_request_success] POST http://100.104.49.22:9200/slc_catalog/_search?size=1000&from=1000 [status:200 request:0.002s]
[2023-03-15 22:18:53,819: INFO/root/run_download] Filtering pending downloads by args.batch_ids=['S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip']
[2023-03-15 22:18:53,819: INFO/root/run_download] len(downloads)=1
[2023-03-15 22:18:53,819: INFO/conf_util/__init__] file: /home/ops/verdi/ops/opera-pcm/conf/settings.yaml
[2023-03-15 22:18:53,836: INFO/root/download_from_asf] Creating directories to process products
[2023-03-15 22:18:53,836: INFO/root/download_from_asf] Processing product_url='s3://asf-ngap2w-p-s1-slc-7b420b89/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip'
[2023-03-15 22:18:53,836: INFO/root/_get_aws_creds] entry
[2023-03-15 22:18:53,836: INFO/root/_get_asf_aws_creds] entry
[2023-03-15 22:19:18,626: INFO/root/download_from_asf] product_filepath=PosixPath('/data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/downloads/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip')
[2023-03-15 22:19:18,626: INFO/root/download_from_asf] Marking as downloaded. product_url='s3://asf-ngap2w-p-s1-slc-7b420b89/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip'
[2023-03-15 22:19:18,626: INFO/__main__/update_document] update_document **kwargs
[2023-03-15 22:19:18,631: INFO/elasticsearch/log_request_success] POST http://100.104.49.22:9200/slc_catalog/_update/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip [status:200 request:0.005s]
[2023-03-15 22:19:18,631: INFO/__main__/mark_product_as_downloaded] Document updated: {'_index': 'slc_catalog', '_type': '_doc', '_id': 'S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip', '_version': 5, 'result': 'updated', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 23, '_primary_term': 1}
[2023-03-15 22:19:18,631: INFO/root/download_from_asf] product_url_downloaded=s3://asf-ngap2w-p-s1-slc-7b420b89/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip
[2023-03-15 22:19:18,631: INFO/root/download_from_asf] adding additional dataset metadata (intersects_north_america)
[2023-03-15 22:19:18,631: INFO/root/extract_one_to_one] Creating dataset directory
[2023-03-15 22:19:18,632: INFO/opera_pcm/create_dataset_id] Product is /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/downloads/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip
[2023-03-15 22:19:18,632: INFO/opera_pcm/create_dataset_id] Derived dataset ID is S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3
[2023-03-15 22:19:18,632: INFO/opera_pcm/extract] Creating dataset directory /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3
[2023-03-15 22:19:18,632: INFO/opera_pcm/extract] Moving /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/downloads/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip to dataset directory
[2023-03-15 22:19:38,298: INFO/opera_pcm/extract_metadata] Found match pattern with type L1_S1_SLC
[2023-03-15 22:19:38,300: INFO/opera_pcm/extract] Created the extracted metadata file: /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.met.json
[2023-03-15 22:19:38,300: INFO/opera_pcm/create_dataset_json] Nor dataset_version nor CompositeReleaseID nor VersionID could not be found in the product metadata. Setting version to 1 in .dataset.json.
[2023-03-15 22:19:38,300: INFO/opera_pcm/create_dataset_json] Setting version field in .dataset.json to 1
[2023-03-15 22:19:38,300: INFO/opera_pcm/create_dataset_json] dataset_info is {'version': '1', 'creation_timestamp': '2023-03-15T22:19:38.300'}
[2023-03-15 22:19:38,300: INFO/opera_pcm/extract] Created the dataset.json file: /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.dataset.json
[2023-03-15 22:19:38,300: INFO/opera_pcm/extract] Successfully created/updated a dataset: /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3
[2023-03-15 22:19:38,300: INFO/root/extract_one_to_one] dataset_dir='/data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3'
[2023-03-15 22:19:38,300: INFO/root/download_from_asf] Downloading associated orbit file
[2023-03-15 22:19:38,300: INFO/root/download_from_asf] Querying for Precise Ephemeris Orbit (POEORB) file
[2023-03-15 22:19:38,301: INFO/opera_pcm/main] Determining Orbit file for input SAFE file /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/downloads/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip
[2023-03-15 22:19:38,302: INFO/opera_pcm/main] Parsed time range 20201012T002639 - 20201012T002707 from SAFE filename
[2023-03-15 22:19:38,302: INFO/opera_pcm/main] Querying for Orbit file(s) from endpoint https://scihub.copernicus.eu/gnss/search
[2023-03-15 22:19:39,768: INFO/opera_pcm/main] Parsing XML response from Orbit query service
[2023-03-15 22:19:39,769: WARNING/root/download_from_asf] No POEORB file could be found, querying for Restituted Orbit (ROEORB) file
[2023-03-15 22:19:39,769: INFO/opera_pcm/main] Determining Orbit file for input SAFE file /data/work/jobs/2023/03/15/22/16/job-WF-slc_download-20230315T221415.498875Z/downloads/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip/S1A_IW_SLC__1SDV_20201012T002639_20201012T002707_034756_040CB8_B3A3.zip
[2023-03-15 22:19:39,769: INFO/opera_pcm/main] Parsed time range 20201012T002639 - 20201012T002707 from SAFE filename
[2023-03-15 22:19:39,769: INFO/opera_pcm/main] Querying for Orbit file(s) from endpoint https://scihub.copernicus.eu/gnss/search
[2023-03-15 22:19:40,279: INFO/opera_pcm/main] Parsing XML response from Orbit query service
Traceback (most recent call last):
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/download.py", line 188, in download_from_asf
    stage_orbit_file.main(stage_orbit_file_args)
  File "/home/ops/verdi/ops/opera-pcm/tools/stage_orbit_file.py", line 485, in main
    orbit_file_request_id) = parse_orbit_file_query_xml(xml_response)
  File "/home/ops/verdi/ops/opera-pcm/tools/stage_orbit_file.py", line 343, in parse_orbit_file_query_xml
    raise NoQueryResultsException('No results returned from parsed query results')
tools.stage_orbit_file.NoQueryResultsException: No results returned from parsed query results

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 297, in <module>
    asyncio.run(run(sys.argv))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 84, in run
    results["download"] = run_download(args, token, es_conn, netloc, username, password, job_id)  # return None
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/download.py", line 86, in run_download
    download_from_asf(session=session, es_conn=es_conn, downloads=downloads, args=args, token=token, job_id=job_id)
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/download.py", line 198, in download_from_asf
    stage_orbit_file.main(stage_orbit_file_args)
  File "/home/ops/verdi/ops/opera-pcm/tools/stage_orbit_file.py", line 485, in main
    orbit_file_request_id) = parse_orbit_file_query_xml(xml_response)
  File "/home/ops/verdi/ops/opera-pcm/tools/stage_orbit_file.py", line 343, in parse_orbit_file_query_xml
    raise NoQueryResultsException('No results returned from parsed query results')
tools.stage_orbit_file.NoQueryResultsException: No results returned from parsed query results
