### ISSUE TITLE
CSLC PGE error w R2 RC4 tag: 

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#428]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

python daac_data_subscriber.py query -c SENTINEL-1A_SLC --release-version=2.0.0-rc.4.0 --native-id=S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-SLC --chunk-size=1 --job-queue=opera-job_worker-slc_data_download

exception in comment below:

### What did you expect?

I expected it to work

**Comment by philipjyoon** [comment]
Exception Type: <class 'RuntimeError'>
Exception Value: Failed to run pipeline {'run_config': {'input_file_group': {'safe_file_path': '/home/compass_user/input_dir/S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3.zip', 'orbit_file_path': '/home/compass_user/input_dir/S1A_OPER_AUX_POEORB_OPOD_20210309T093131_V20151102T225943_20151104T005943.EOF'}, 'dynamic_ancillary_file_group': {'dem_file': '/home/compass_user/input_dir/dem.vrt'}, 'static_ancillary_file_group': {'burst_database_file': '/home/compass_user/input_dir/opera_burst_database.sqlite3'}, 'product_path_group': {'product_version': '0.0', 'product_path': '/home/compass_user/output_dir', 'scratch_path': '/home/compass_user/output_dir/scratch_dir'}, 'processing': {'polarization': 'co-pol'}, 'cnm_version': None, 'localize': ['s3://opera-int-rs-pop1/inputs/SLC/S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3/S1A_OPER_AUX_POEORB_OPOD_20210309T093131_V20151102T225943_20151104T005943.EOF'], 'simulate_outputs': False}, 'pge_config': {'runconfig': {'input_file_group': {'safe_file_path': '__CHIMERA_VAL__', 'orbit_file_path': '__CHIMERA_VAL__'}, 'dynamic_ancillary_file_group': {'dem_file': '__CHIMERA_VAL__'}, 'static_ancillary_file_group': {'burst_database_file': '__CHIMERA_VAL__'}, 'product_path_group': {'product_version': '__CHIMERA_VAL__', 'product_path': '/home/compass_user/output_dir', 'scratch_path': '/home/compass_user/output_dir/scratch_dir'}, 'processing': {'polarization': 'co-pol'}, 'cnm_version': '__CHIMERA_VAL__'}, 'preconditions': ['get_product_version', 'get_slc_s1_safe_file', 'get_slc_s1_orbit_file', 'get_slc_s1_dem', 'get_slc_s1_burst_database', 'get_cnm_version', 'set_daac_product_type'], 'postprocess': ['update_product_accountability'], 'get_product_version': {'version_key': 'CSLC_S1_PRODUCT_VERSION'}, 'get_slc_s1_dem': {'s3_bucket': 'opera-dem'}, 'get_slc_s1_burst_database': {'s3_bucket': 'opera-burstdb', 's3_key': 'opera_burst_database_deploy_2022_1212.sqlite3'}, 'set_daac_product_type': {'template': 'OPERA_L2_CSLC_S1_{cnm_version}'}, 'set_extra_pge_output_metadata': {'daac_product_type': 'daac_product_type'}, 'output_types': {'L2_CSLC': ['h5', 'catalog.json', 'iso.xml', 'log', 'qa.log']}, 'pge_name': 'L2_CSLC_S1', 'primary_input': 'L1_S1_SLC', 'primary_output': 'L2_CSLC_S1', 'localize_groups': ['input_file_group', 'dynamic_ancillary_file_group', 'static_ancillary_file_group'], 'input_file_base_name_regexes': ['(?P<mission_id>S1A|S1B)_(?P<beam_mode>IW)_(?P<product_type>SLC)(?P<resolution>_)_(?P<level>1)(?P<class>S)(?P<pol>SH|SV|DH|DV)_(?P<start_ts>(?P<start_year>\\d{4})(?P<start_month>\\d{2})(?P<start_day>\\d{2})T(?P<start_hour>\\d{2})(?P<start_minute>\\d{2})(?P<start_second>\\d{2}))_(?P<stop_ts>(?P<stop_year>\\d{4})(?P<stop_month>\\d{2})(?P<stop_day>\\d{2})T(?P<stop_hour>\\d{2})(?P<stop_minute>\\d{2})(?P<stop_second>\\d{2}))_(?P<orbit_num>\\d{6})_(?P<data_take_id>[0-9A-F]{6})_(?P<product_id>[0-9A-F]{4})$'], 'output_base_name': 'OPERA_L2_CSLC-S1A_IW_{burst_id}_{pol}_{acquisition_ts}Z_{product_version}_{creation_ts}Z', 'ancillary_base_name': 'OPERA_L2_CSLC-S1A_IW_{pol}_{product_version}_{creation_ts}Z'}, 'localize_urls': [{'url': 's3://opera-int-rs-pop1/inputs/SLC/S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3/S1A_OPER_AUX_POEORB_OPOD_20210309T093131_V20151102T225943_20151104T005943.EOF', 'path': 'input/'}], 'simulate_outputs': False, 'job_specification': {'command': '/home/ops/verdi/ops/chimera/chimera/run_sciflo.sh', 'container': 'container-nasa_opera-sds-pcm:2.0.0-rc.4.0', 'dependency_images': [{'container_image_id': 'sha256:4689e4e24241e1dfe70803864353e4345f66180cbad9a80781599b70b053b77c', 'container_image_name': 'opera_pge/cslc_s1:2.0.0-er.5.0', 'container_image_url': 's3://s3-us-west-2.amazonaws.com/opera-int-cc-pop1/opera_pge-cslc_s1-2.0.0-er.5.0.tar.gz', 'container_mappings': {'$HOME/.aws': ['/root/.aws', 'ro'], '$HOME/.netrc': ['/root/.netrc']}}], 'disk_usage': '70GB', 'id': 'job-SCIFLO_L2_CSLC_S1:2.0.0-rc.4.0', 'imported_worker_files': {'$HOME/.aws': '/home/ops/.aws', '$HOME/.netrc': '/home/ops/.netrc', '$HOME/verdi/etc/settings.yaml': '/home/ops/verdi/ops/opera-pcm/conf/settings.yaml'}, 'job-version': '2.0.0-rc.4.0', 'params': [{'destination': 'positional', 'name': 'module_path', 'value': '/home/ops/verdi/ops/opera-pcm'}, {'destination': 'positional', 'name': 'wf_dir', 'value': '/home/ops/verdi/ops/opera-pcm/opera_chimera/wf_xml'}, {'destination': 'positional', 'name': 'wf_name', 'value': 'L2_CSLC_S1'}, {'destination': 'context', 'name': 'product_path', 'value': 's3://s3-us-west-2.amazonaws.com:80/opera-int-rs-pop1/inputs/SLC/S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3'}, {'destination': 'context', 'name': 'dataset_type', 'value': 'L1_S1_SLC'}, {'destination': 'context', 'name': 'input_dataset_id', 'value': 'S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3'}, {'destination': 'context', 'name': 'product_metadata', 'value': {'metadata': {'FileLocation': '/data/work/jobs/2023/03/15/22/20/job-WF-slc_download-20230315T221543.865705Z/S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3', 'FileName': 'S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3.zip', 'FileSize': 5259633837, 'ProductReceivedDay': '15', 'ProductReceivedMonth': '03', 'ProductReceivedTime': '2023-03-15T22:23:02.067819Z', 'ProductReceivedYear': 2023, 'ProductType': 'L1_S1_SLC', 'beam_mode': 'IW', 'class': 'S', 'data_take_id': '00BEDF', 'format': 'zip', 'id': 'S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3', 'intersects_north_america': True, 'level': 1, 'mission_id': 'S1A', 'orbit_num': 8440, 'pol': 'DV', 'processing_mode': 'forward', 'product_id': '10B3', 'product_type': 'SLC', 'resolution': '_', 'start_day': 3, 'start_hour': 12, 'start_minute': 22, 'start_month': 11, 'start_second': 42, 'start_ts': '2015-11-03T12:22:42.000000Z', 'start_year': 2015, 'stop_day': 3, 'stop_hour': 12, 'stop_minute': 23, 'stop_month': 11, 'stop_second': 12, 'stop_ts': '2015-11-03T12:23:12.000000Z', 'stop_year': 2015}}}, {'destination': 'context', 'name': 'accountability_module_path', 'value': 'opera_chimera.accountability'}, {'destination': 'context', 'name': 'accountability_class', 'value': 'OperaAccountability'}, {'destination': 'context', 'name': 'pge_runconfig_dir', 'value': 'pge_runconfig_dir'}, {'destination': 'context', 'name': 'pge_input_dir', 'value': 'pge_input_dir'}, {'destination': 'context', 'name': 'pge_output_dir', 'value': 'pge_output_dir'}, {'destination': 'context', 'name': 'container_home', 'value': '/home/compass_user'}], 'post': ['hysds.triage.triage'], 'recommended-queues': ['opera-job_worker-sciflo-l2_cslc_s1'], 'resource': 'jobspec', 'soft_time_limit': 9300, 'time_limit': 9360}}: Got exception running:
docker run --init --rm -u 1006:1006 -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_runconfig_dir:/home/compass_user/runconfig:ro -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_input_dir:/home/compass_user/input_dir:ro -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_output_dir:/home/compass_user/output_dir opera_pge/cslc_s1:2.0.0-er.5.0 --file /home/compass_user/runconfig/RunConfig.yaml
STDOUT/STDERR:
Running preprocessor for CslcS1PreProcessorMixin
Starting SAS execution for CslcS1Executor
Traceback (most recent call last):
File "/home/compass_user/opera/scripts/pge_main.py", line 187, in <module>
pge_main()
File "/home/compass_user/opera/scripts/pge_main.py", line 183, in pge_main
pge_start(run_config_filename)
File "/home/compass_user/opera/scripts/pge_main.py", line 157, in pge_start
pge.run()
File "/home/compass_user/opera/pge/base/base_pge.py", line 743, in run
self.run_sas_executable(**kwargs)
File "/home/compass_user/opera/pge/base/base_pge.py", line 722, in run_sas_executable
elapsed_time = time_and_execute(
File "/home/compass_user/opera/util/run_utils.py", line 214, in time_and_execute
logger.critical(module_name, ErrorCode.SAS_PROGRAM_FAILED, error_msg)
File "/home/compass_user/opera/util/logger.py", line 407, in critical
raise RuntimeError(description)
RuntimeError: Command "/home/compass_user/miniconda3/bin/conda run -n COMPASS s1_cslc.py /home/compass_user/output_dir/scratch_dir/RunConfig_sas.yaml" failed with exit code 1

Traceback (most recent call last):
File "/home/ops/verdi/ops/opera-pcm/util/exec_util.py", line 41, in call_noerr
output = check_output(cmd, stderr=STDOUT, shell=True)
File "/opt/conda/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/opt/conda/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker run --init --rm -u 1006:1006 -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_runconfig_dir:/home/compass_user/runconfig:ro -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_input_dir:/home/compass_user/input_dir:ro -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_output_dir:/home/compass_user/output_dir opera_pge/cslc_s1:2.0.0-er.5.0 --file /home/compass_user/runconfig/RunConfig.yaml' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/opera-pcm/opera_chimera/opera_pge_job_submitter.py", line 168, in perform_adaptation_tasks
output_datasets = run_pipeline(job_json, self._base_work_dir)
File "/home/ops/verdi/ops/opera-pcm/wrapper/opera_pge_wrapper.py", line 104, in run_pipeline
exec_pge_command(
File "/home/ops/verdi/ops/opera-pcm/wrapper/opera_pge_wrapper.py", line 199, in exec_pge_command
call_noerr(cmd_line, work_dir)
File "/home/ops/verdi/ops/opera-pcm/util/exec_util.py", line 54, in call_noerr
raise RuntimeError("Got exception running:\n{}\nSTDOUT/STDERR:\n{}".format(cmd, e.output.decode()))
RuntimeError: Got exception running:
docker run --init --rm -u 1006:1006 -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_runconfig_dir:/home/compass_user/runconfig:ro -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_input_dir:/home/compass_user/input_dir:ro -v /data/work/jobs/2023/03/15/22/28/SCIFLO_L2_CSLC_S1__2.0.0-rc.4.0-S1A_IW_SLC__1SDV_20151103T122242_20151103T122312_008440_00BEDF_10B3-20230315T222430.356557Z/pge_output_dir:/home/compass_user/output_dir opera_pge/cslc_s1:2.0.0-er.5.0 --file /home/compass_user/runconfig/RunConfig.yaml
STDOUT/STDERR:
Running preprocessor for CslcS1PreProcessorMixin
Starting SAS execution for CslcS1Executor
Traceback (most recent call last):
File "/home/compass_user/opera/scripts/pge_main.py", line 187, in <module>
pge_main()
File "/home/compass_user/opera/scripts/pge_main.py", line 183, in pge_main
pge_start(run_config_filename)
File "/home/compass_user/opera/scripts/pge_main.py", line 157, in pge_start
pge.run()
File "/home/compass_user/opera/pge/base/base_pge.py", line 743, in run
self.run_sas_executable(**kwargs)
File "/home/compass_user/opera/pge/base/base_pge.py", line 722, in run_sas_executable
elapsed_time = time_and_execute(
File "/home/compass_user/opera/util/run_utils.py", line 214, in time_and_execute
logger.critical(module_name, ErrorCode.SAS_PROGRAM_FAILED, error_msg)
File "/home/compass_user/opera/util/logger.py", line 407, in critical
raise RuntimeError(description)
RuntimeError: Command "/home/compass_user/miniconda3/bin/conda run -n COMPASS s1_cslc.py /home/compass_user/output_dir/scratch_dir/RunConfig_sas.yaml" failed with exit code 1
