### ISSUE TITLE
[Bug]: 9 cnm notify jobs failed during R2 global run started on 5-4-2023 on INT-FWD

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#496]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

We performed a global run of SLC data date ranging from 4-11-2021 to 4-22-2021. 9 CNM send jobs failed w the error below.

```
Traceback (most recent call last):
File "/home/ops/verdi/ops/CNM_product_delivery/product_delivery/commons/exec_util.py", line 15, in wrapper
status = func(*args, **kwargs)
File "/home/ops/verdi/ops/CNM_product_delivery/product_delivery/scripts/../utils/send_notify_msg.py", line 262, in main
raise RuntimeError(
RuntimeError: Could not find a product in "/data/work/jobs/2023/05/05/22/53/send_notify_msg__2.0.0-rc.6.0-OPERA_L2_RTC-S1_T020-041075-IW1_20210415T012807Z_20230505T184829Z_S1B_30_v0.0-20230505T202225.392872Z/OPERA_L2_RTC-S1_T020-041075-IW1_20210415T012807Z_20230505T184829Z_S1B_30_v0.0" matching the glob pattern "*.png"
```

Here are the 9 jobs that failed. Looking at the S3 RS products folder, all output seem correct.

- OPERA_L2_RTC-S1_T020-041075-IW1_20210415T012807Z_20230505T184829Z_S1B_30_v0.0-20230505T202225.392872Z
- OPERA_L2_RTC-S1_T153-326888-IW2_20210412T042718Z_20230505T105750Z_S1B_30_v0.0-20230505T115927.184960Z
- OPERA_L2_RTC-S1_T080-170759-IW2_20210413T045033Z_20230505T055706Z_S1A_30_v0.0-20230510T212426.294979Z
- OPERA_L2_RTC-S1_T068-145176-IW1_20210412T091427Z_20230505T004046Z_S1A_30_v0.0-20230505T014605.68166Z
- OPERA_L2_RTC-S1_T072-152930-IW3_20210412T151057Z_20230504T230816Z_S1A_30_v0.0-20230505T000404.630646Z
- OPERA_L2_RTC-S1_T141-301834-IW2_20210411T091532Z_20230504T205146Z_S1B_30_v0.0-20230504T215827.721801Z
- OPERA_L2_RTC-S1_T141-301959-IW2_20210411T092117Z_20230504T205041Z_S1B_30_v0.0-20230504T215049.340468Z
- OPERA_L2_RTC-S1_T142-303920-IW1_20210411T105125Z_20230504T202118Z_S1B_30_v0.0-20230504T213745.223593Z
- OPERA_L2_RTC-S1_T145-309483-IW2_20210411T150710Z_20230504T195238Z_S1B_30_v0.0-20230504T205305.871550Z

### What did you expect?

These cnm send jobs to succeed

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by philipjyoon** [comment]
Input granules for the first 3 jobs:

S1B_IW_SLC__1SDV_20210415T012756_20210415T012823_026471_0328FF_1A38
S1B_IW_SLC__1SDV_20210412T042700_20210412T042727_026429_0327AA_7A06
S1A_IW_SLC__1SDV_20210413T045033_20210413T045100_037427_046963_09E3

**Comment by philipjyoon** [comment]
Last 6:
S1A_IW_SLC__1SDV_20210412T091417_20210412T091444_037415_0468F9_C0DC
S1A_IW_SLC__1SDV_20210412T151045_20210412T151112_037419_046917_355B
S1B_IW_SLC__1SDV_20210411T091524_20210411T091551_026417_032752_450C
S1B_IW_SLC__1SDV_20210411T092108_20210411T092135_026417_032753_D9C2
S1B_IW_SLC__1SDV_20210411T105104_20210411T105131_026418_03275C_6B9F
S1B_IW_SLC__1SDV_20210411T150653_20210411T150721_026421_032773_BE19

**Comment by philipjyoon** [comment]
This error is transient. All these 9 granules produced 100% successful CNM-S jobs when tried again on a different cluster.
