### ISSUE TITLE
[Bug]: Network Timeouts and Lack of Retries in CMR Script

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-pcm#590]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

While running the CMR audit script, we encountered a `504 Gateway Time-out` error when making network requests to the CMR server. The script may lack a robust retry mechanism to handle transient network errors, leading to potential failures. Additionally the script may just be making too many queries to the CMR server leading to the server to timeout our requests. 

Here's an example of the error message (full log [here](https://github.com/nasa/opera-sds-pcm/files/12402457/cmr_audit_log.txt)):
```
ERROR:  815321 backoff:_common.py:_log_giveup:120 - Giving up fetch_post_url(...) after 3 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Time-out', url=URL('https://cmr.earthdata.nasa.gov/search/granules.umm_json'))
Traceback (most recent call last):
  File "cmr_audit_hls.py", line 251, in <module>
    asyncio.run(run(sys.argv))
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "cmr_audit_hls.py", line 193, in run
    cmr_granules_s30, cmr_granules_s30_details = await async_get_cmr_granules_hls_s30(temporal_date_start=cmr_start_dt_str, temporal_date_end=cmr_end_dt_str)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cmr_audit_hls.py", line 68, in async_get_cmr_granules_hls_s30
    return await async_get_cmr_granules(collection_short_name="HLSS30",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/CMR_audit-a2xVdMf9/lib/python3.11/site-packages/tools/ops/cmr_audit/cmr_audit_utils.py", line 78, in async_get_cmr_granules
    await asyncio.gather(*task_chunk, return_exceptions=False))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/CMR_audit-a2xVdMf9/lib/python3.11/site-packages/tools/ops/cmr_audit/cmr_client.py", line 31, in async_cmr_post
    async with await fetch_post_url(session, url, data, headers) as response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/CMR_audit-a2xVdMf9/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/CMR_audit-a2xVdMf9/lib/python3.11/site-packages/tools/ops/cmr_audit/cmr_client.py", line 75, in fetch_post_url
    return await session.post(url, data=data, headers=headers, raise_for_status=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/share/virtualenvs/CMR_audit-a2xVdMf9/lib/python3.11/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/.local/share/virtualenvs/CMR_audit-a2xVdMf9/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Time-out', url=URL('https://cmr.earthdata.nasa.gov/search/granules.umm_json')
```

### What did you expect?

We expected the script to successfully fetch data from the CMR server without any network errors. In case of transient network issues, we expected the script to have a retry mechanism to handle such errors gracefully.

### Reproducible steps

1. Set up the environment variables as required by the script.
2. Run the `cmr_audit_hls.py` script with the desired date range, for example we used `--start-datetime 2023-06-10T00:00:00Z  --end-datetime 2023-06-20T00:00:00Z`
3. Monitor the logs to observe the 504 Gateway Time-out error when making requests to the CMR server (this doesn't always happens but happens sometimes). 

### Environment

- Version of this software PCM R1-latest
- Operating System: Linux
- Framework: Python with `asyncio` and `aiohttp` libraries
- Time-of-day: ~11AM PST

**Comment by riverma** [comment]
## Some suggestions

### Use retries and exponential backoff:
Try improving the `fetch_post_url` function to include a retry mechanism using `backoff`.

e.g. in [this code](https://github.com/nasa/opera-sds-pcm/blob/develop/tools/ops/cmr_audit/cmr_client.py#L74)
```
import backoff
import aiohttp

@backoff.on_exception(backoff.expo, aiohttp.ClientResponseError, max_tries=5)
async def fetch_post_url(session: aiohttp.ClientSession, url, data: str, headers):
    return await session.post(url, data=data, headers=headers, raise_for_status=True)
```

### Be cognizant of rate limits:
If the CMR server provides headers (or docs) indicate rate limits or request limits, make sure the script respects these limits by introducing delays between requests.

### Concurrency management:

Use a semaphore or other concurrency technique to limit the number of simultaneous requests. Looks like there's dozens of requests happening in a short period of time. This might be overloading the CMR server.

**Comment by riverma** [comment]
Hey @chrisjrd - I think a semaphore approach makes sense. 

Please see the "Reproducible Steps" section above. Based on conversations with @LalaP, it seems the script is failing at least `10` times before she gave up. Most recently `5` times today. I think the success criteria for the resolution to this ticket should be that the script only needs to be run a single time, and that transient network issues like a `504` are dealt with internally within the script.
