### ISSUE TITLE
[Bug]: Missing ionsphere files for HIST Processing 2021-04-14 to 2021-04-25

### ISSUE THREAD

**Issue by toandn-jpl** [nasa/opera-sds-pcm#673]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Major of HIST 2021-04-14 to 2021-04-25 are running into issues of missing Ionosphere  when attempted to run trigger-SCIFLO_L2_CSLC_S1.

```
Exception Type: <class 'RuntimeError'>
Exception Value: Input precondition failure: Could not find an Ionosphere file within the S3 location s3://s3-us-west-2.amazonaws.com:80/opera-int-rs-fwd/inputs/SLC/S1A_IW_SLC__1SDV_20210414T021838_20210414T021904_037440_0469DF_F76C-r7
Traceback (most recent call last):
  File "/home/ops/verdi/ops/chimera/chimera/precondition_evaluator.py", line 167, in evaluate
    job_params.update(cls_object.run(self._pge_config.get(ChimeraConstants.PRECONDITIONS, list())))
  File "/home/ops/verdi/ops/chimera/chimera/precondition_functions.py", line 17, in run
    self._job_params.update(getattr(self, func)())
  File "/home/ops/verdi/ops/opera-pcm/opera_chimera/precondition_functions.py", line 542, in get_slc_s1_tec_file
    raise RuntimeError(
RuntimeError: Could not find an Ionosphere file within the S3 location s3://s3-us-west-2.amazonaws.com:80/opera-int-rs-fwd/inputs/SLC/S1A_IW_SLC__1SDV_20210414T021838_20210414T021904_037440_0469DF_F76C-r7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ops/verdi/ops/sciflo-1.3.6/sciflo/grid/workUnit.py", line 130, in run
    result = self._run()
  File "/home/ops/verdi/ops/sciflo-1.3.6/sciflo/grid/workUnit.py", line 172, in _run
    return func(*funcArgs)
  File "/tmp/scifloWork-ops/sciflowuid-57849622-11532180-0099132023-b758cfb914d2b25ab6c146a6b1a066c3/input_preprocessor.py", line 28, in process
    output_context = pre_cond_evaluator.evaluate()
  File "/home/ops/verdi/ops/chimera/chimera/precondition_evaluator.py", line 172, in evaluate
    raise RuntimeError("Input precondition failure: {}".format(e))
RuntimeError: Input precondition failure: Could not find an Ionosphere file within the S3 location s3://s3-us-west-2.amazonaws.com:80/opera-int-rs-fwd/inputs/SLC/S1A_IW_SLC__1SDV_20210414T021838_20210414T021904_037440_0469DF_F76C-r7
```

### What did you expect?

I expected [...]

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by hhlee445** [comment]
"include_regions": "north_america_opera" needs to be defined for the HIST batch job.  we will make include_regions as required parameter for the historical processing.
