### ISSUE TITLE
[Bug]: cmr_audit_slc.py failing with 'Bad Request' error

### ISSUE THREAD

**Issue by LalaP** [nasa/opera-sds-pcm#690]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When OPS team tried to run the cmr_audit_slc.py it is failing with the following error:

~/mozart/ops/<hostname>-2.1.1/tools/ops/cmr_audit$ python cmr_audit_slc.py --start-datetime 2023-10-20T00:00  --end-datetime 2023-10-21T02:59:59
   INFO:     141 root:cmr_audit_slc.py:run:235 - argv=['cmr_audit_slc.py', '--start-datetime', '2023-10-20T00:00', '--end-datetime', '2023-10-21T02:59:59']
   INFO:     142 root:cmr_audit_slc.py:run:238 - Querying CMR for list of expected SLC granules
   INFO:    1225 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=268
   INFO:    1240 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=89
   INFO:    1711 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=263
   INFO:    1712 tools.ops.cmr_audit.cmr_audit_utils:cmr_audit_utils.py:async_get_cmr_granules:85 - SENTINEL-1A_SLC len(cmr_granules)=620
   INFO:    1951 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    2090 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    3091 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    3092 tools.ops.cmr_audit.cmr_audit_utils:cmr_audit_utils.py:async_get_cmr_granules:85 - SENTINEL-1B_SLC len(cmr_granules)=0
   INFO:    3092 root:cmr_audit_slc.py:run:248 - Filtering North America granules
   INFO:    5730 root:cmr_audit_slc.py:run:267 - Expected CSLC input (granules): len(cmr_granules_slc_na)=69
   INFO:    5730 root:cmr_audit_slc.py:run:268 - Expected RTC input (granules): len(cmr_granules_slc)=620
   INFO:    5733 root:cmr_audit_slc.py:run:282 - Querying CMR for list of expected CSLC granules
WARNING:    5733 root:cmr_audit_slc.py:async_get_cmr:102 - PRODUCTION: Using CMR environment. request_url='https://cmr.earthdata.nasa.gov/search/granules.umm_json'
   INFO:    5733 root:cmr_audit_slc.py:async_get_cmr:128 - Processing batch 1 of 1
  ERROR:    5859 backoff:_common.py:_log_giveup:120 - Giving up fetch_post_url(...) after 1 tries (aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://cmr.earthdata.nasa.gov/search/granules.umm_json'))
Traceback (most recent call last):
  File "/export/home/hysdsops/mozart/ops/<hostname>-2.1.1/tools/ops/cmr_audit/cmr_audit_slc.py", line 360, in <module>
    asyncio.run(run(sys.argv))
  File "/export/home/hysdsops/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/export/home/hysdsops/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/export/home/hysdsops/mozart/ops/<hostname>-2.1.1/tools/ops/cmr_audit/cmr_audit_slc.py", line 283, in run
    cmr_cslc_products = await async_get_cmr_cslc(cslc_native_id_patterns, temporal_date_start=cmr_start_dt_str, temporal_date_end=cmr_end_dt_str)
  File "/export/home/hysdsops/mozart/ops/<hostname>-2.1.1/tools/ops/cmr_audit/cmr_audit_slc.py", line 80, in async_get_cmr_cslc
    return await async_get_cmr(cslc_native_id_patterns, collection_short_name="OPERA_L2_CSLC-S1_V1", 
  File "/export/home/hysdsops/mozart/ops/<hostname>-2.1.1/tools/ops/cmr_audit/cmr_audit_slc.py", line 131, in async_get_cmr
    await asyncio.gather(*task_chunk, return_exceptions=False)
  File "/export/home/hysdsops/mozart/ops/opera-pcm/tools/ops/cmr_audit/cmr_client.py", line 36, in async_cmr_post
    async with await fetch_post_url(session, url, data, headers) as response:
  File "/export/home/hysdsops/mozart/lib/python3.9/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/export/home/hysdsops/mozart/ops/opera-pcm/tools/ops/cmr_audit/cmr_client.py", line 80, in fetch_post_url
    return await session.post(url, data=data, headers=headers, raise_for_status=raise_for_status)
  File "/export/home/hysdsops/mozart/lib/python3.9/site-packages/aiohttp/client.py", line 689, in _request
    resp.raise_for_status()
  File "/export/home/hysdsops/mozart/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://cmr.earthdata.nasa.gov/search/granules.umm_json')

### What did you expect?

I expected teh report to run and list the missing granules

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by chrisjrd** [comment]
we can add validation to enforce the formatting. But simultaneously, current processes should be updated to mention the full ISO-8601 format requirement.
For reference, the format we and CMR typically expect is `YYYY-MM-DDTHHmmSSZ`, compliant with ISO-8601 and RFC-3339. Other formats may be supported by CMR, but users should prefer and consistently use the full ISO-8601 for guaranteed results.

**Comment by toandn-jpl** [comment]
Confirmed working with `YYYY-MM-DDTHHmmSSZ` format.

```
(mozart) hysdsops@opera-ops-mozart-fwd:~/mozart/ops/opera-sds-pcm-2.1.1$ python tools/ops/cmr_audit/cmr_audit_slc.py --start-datetime 2023-10-01T00:00:00Z  --end-datetime 2023-10-30T23:59:59Z
   INFO:     141 root:cmr_audit_slc.py:run:235 - argv=['tools/ops/cmr_audit/cmr_audit_slc.py', '--start-datetime', '2023-10-01T00:00:00Z', '--end-datetime', '2023-10-30T23:59:59Z']
   INFO:     143 root:cmr_audit_slc.py:run:238 - Querying CMR for list of expected SLC granules
   INFO:    1243 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=283
   INFO:    1506 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=320
   INFO:    2020 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=274
   INFO:    2064 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=254
   INFO:    2114 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=256
   INFO:    2407 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=313
   INFO:    2476 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=258
   INFO:    2492 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=285
   INFO:    2506 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=250
   INFO:    2600 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=255
   INFO:    2614 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=271
   INFO:    2626 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=262
   INFO:    2811 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=276
   INFO:    3035 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=283
   INFO:    3051 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=308
   INFO:    3388 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=294
   INFO:    3610 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=270
   INFO:    3782 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=284
   INFO:    3831 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=274
   INFO:    3945 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=246
   INFO:    4197 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=247
   INFO:    4320 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=287
   INFO:    4333 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=262
   INFO:    4463 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=313
   INFO:    4506 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=326
   INFO:    4727 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=256
   INFO:    4747 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=294
   INFO:    4759 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=273
   INFO:    4774 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=263
   INFO:    4814 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=294
   INFO:    4846 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=273
   INFO:    4965 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=279
   INFO:    5502 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=250
   INFO:    5605 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=320
   INFO:    5627 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=255
   INFO:    5928 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=271
   INFO:    6297 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=271
   INFO:    6315 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=282
   INFO:    6431 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=279
   INFO:    6501 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=308
   INFO:    6636 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=268
   INFO:    7031 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=263
   INFO:    7052 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=262
   INFO:    7065 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=287
   INFO:    7077 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=288
   INFO:    7089 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=284
   INFO:    7147 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=186
   INFO:    7258 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=326
   INFO:    7278 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=282
   INFO:    7286 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=93
   INFO:    7380 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=243
   INFO:    7463 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=259
   INFO:    7483 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=244
   INFO:    7923 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=295
   INFO:    7924 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    7938 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=248
   INFO:    7951 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=274
   INFO:    7966 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=285
   INFO:    8605 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=227
   INFO:    8819 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=254
   INFO:    8822 tools.ops.cmr_audit.cmr_audit_utils:cmr_audit_utils.py:async_get_cmr_granules:85 - SENTINEL-1A_SLC len(cmr_granules)=15,980
   INFO:    9165 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9169 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9170 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9183 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9185 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9188 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9206 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9208 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9210 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9212 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9212 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9213 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9221 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9225 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9312 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9446 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9478 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9483 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9484 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9500 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9521 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9522 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9527 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9545 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9566 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9566 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9570 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9581 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9590 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9592 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9740 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9754 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9761 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9788 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9806 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9807 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9821 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9830 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9831 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9841 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9844 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9848 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9866 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9881 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9886 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9993 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:    9996 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10027 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10063 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10081 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10085 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10087 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10101 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10105 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10105 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10110 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10120 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10134 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10138 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10140 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   10141 tools.ops.cmr_audit.cmr_audit_utils:cmr_audit_utils.py:async_get_cmr_granules:85 - SENTINEL-1B_SLC len(cmr_granules)=0
   INFO:   10143 root:cmr_audit_slc.py:run:248 - Filtering North America granules
   INFO:   71077 root:cmr_audit_slc.py:run:267 - Expected CSLC input (granules): len(cmr_granules_slc_na)=1,843
   INFO:   71078 root:cmr_audit_slc.py:run:268 - Expected RTC input (granules): len(cmr_granules_slc)=15,980
   INFO:   71121 root:cmr_audit_slc.py:run:282 - Querying CMR for list of expected CSLC granules
WARNING:   71121 root:cmr_audit_slc.py:async_get_cmr:102 - PRODUCTION: Using CMR environment. request_url='https://cmr.earthdata.nasa.gov/search/granules.umm_json'
   INFO:   71121 root:cmr_audit_slc.py:async_get_cmr:128 - Processing batch 1 of 1
   INFO:   75363 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   75908 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=0
   INFO:   75908 root:cmr_audit_slc.py:run:285 - Querying CMR for list of expected RTC granules
WARNING:   75909 root:cmr_audit_slc.py:async_get_cmr:102 - PRODUCTION: Using CMR environment. request_url='https://cmr.earthdata.nasa.gov/search/granules.umm_json'
   INFO:   75910 root:cmr_audit_slc.py:async_get_cmr:128 - Processing batch 1 of 1
   INFO:  174877 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=930
   INFO:  175266 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=911
   INFO:  175366 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=959
   INFO:  180019 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=932
   INFO:  182990 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=958
   INFO:  187364 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=933
   INFO:  189461 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=903
   INFO:  190804 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=966
   INFO:  207055 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=927
   INFO:  207968 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=931
   INFO:  208750 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=929
   INFO:  209608 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=941
   INFO:  210589 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=953
   INFO:  213476 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=934
   INFO:  214976 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=961
   INFO:  230215 tools.ops.cmr_audit.cmr_client:cmr_client.py:async_cmr_post:40 - CMR number of granules (cmr-query): response_json["hits"]=907
   INFO:  230532 root:cmr_audit_slc.py:run:309 - Expected input (granules): len(cmr_granules_slc)=15,980
   INFO:  230532 root:cmr_audit_slc.py:run:310 - Fully published (granules) (CSLC): len(cmr_cslc_products)=0
   INFO:  230532 root:cmr_audit_slc.py:run:311 - Fully published (granules) (RTC): len(cmr_rtc_products)=14,975
   INFO:  230532 root:cmr_audit_slc.py:run:312 - Missing processed CSLC (granules): len(missing_cmr_granules_slc_cslc)=1,843
   INFO:  230532 root:cmr_audit_slc.py:run:313 - Missing processed RTC (granules): len(missing_cmr_granules_slc_rtc)=3,087
   INFO:  230532 root:cmr_audit_slc.py:run:328 - Writing granule list to file 'missing_granules_SLC-CSLC_20231001-000000ZZ_20231030-235959ZZ_20231130-153253Z.txt'
   INFO:  230532 root:cmr_audit_slc.py:run:331 - Finished writing to file 'missing_granules_SLC-CSLC_20231001-000000ZZ_20231030-235959ZZ_20231130-153253Z.txt'
   INFO:  230532 root:cmr_audit_slc.py:run:334 - Writing granule list to file 'missing_granules_SLC-RTC_20231001-000000ZZ_20231030-235959ZZ_20231130-153253Z.txt'
   INFO:  230533 root:cmr_audit_slc.py:run:337 - Finished writing to file 'missing_granules_SLC-RTC_20231001-000000ZZ_20231030-235959ZZ_20231130-153253Z.txt'
   ```
