### ISSUE TITLE
[Bug]: DISP-S1 logic is likely adding incorrect CSLC granule into triggering, resulting in more than one DISP-S1 products being generated

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#887]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

During I&T of 3.1.0_rc.2.0 we observed the following stacktrace in DISP-S1 SCIFLO job:

```Traceback (most recent call last):
  File "/home/mamba/opera/scripts/pge_main.py", line 190, in <module>
    pge_main()
  File "/home/mamba/opera/scripts/pge_main.py", line 186, in pge_main
    pge_start(run_config_filename)
  File "/home/mamba/opera/scripts/pge_main.py", line 160, in pge_start
    pge.run()
  File "/home/mamba/opera/pge/base/base_pge.py", line 762, in run
    self.run_postprocessor(**kwargs)
  File "/home/mamba/opera/pge/disp_s1/disp_s1_pge.py", line 805, in run_postprocessor
    self._validate_output()
  File "/home/mamba/opera/pge/disp_s1/disp_s1_pge.py", line 175, in _validate_output
    self.logger.critical(self.name, ErrorCode.INVALID_OUTPUT, error_msg)
  File "/home/mamba/opera/util/logger.py", line 407, in critical
    raise RuntimeError(description)
RuntimeError: The SAS created too many files with the expected '.nc' extension: ['/home/mamba/output_dir/20240510_20240615.unw.nc', '/home/mamba/output_dir/20240510_20240603.unw.nc']```

Triaged job link:
http://opera-int-triage-pop1.s3-website-us-west-2.amazonaws.com/triaged_job-job-WF-SCIFLO_L3_DISP_S1-20240620T221510.118650Z_task-56b20023-fdc7-4187-99e0-aa2fd2381da2

### What did you expect?
n/t

### Reproducible steps

```bash
python /export/home/hysdsops/mozart/ops/opera-pcm/data_subscriber/daac_data_subscriber.py query --collection-shortname OPERA_L2_CSLC-S1_V1 --release-version=3.1.0-rc.2.0 --job-queue=opera-job_worker-cslc_data_download --chunk-size=1 --processing-mode=reprocessing --m=1 --k=4  --start-date 2024-06-15T00:00:00Z  --end-date 2024-06-15T02:00:00Z --use-temporal
```

**Comment by philipjyoon** [comment]
This bug is likely fixed in branch https://github.com/nasa/opera-sds-pcm/tree/832_disp_s1_trigger_major_design_change which will be merged into `develop` soon. I recommend testing it one more time after a release has been made.
