### ISSUE TITLE
[Bug]: Automated PGE smoke test for DSWx-S1 is broken in 3.0.0-rc.6.0

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#926]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

The smoke test failed after running for 40 mins. According to @collinss-jpl this is most likely due to the wrong version being labeled in this release.

http://opera-int-triage-fwd.s3-website-us-west-2.amazonaws.com/triaged_job-pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z_task-1ed549b2-1fe7-447d-af87-7fb94050d021

```
##########################################
Starting PGE integration smoke test for dswx_s1: Fri Jul 19 01:19:56 UTC 2024
Working dir is /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z
Version tag for dswx_s1 is 3.0.0-rc.2.1
Cloning opera-sds-pge repository
Cloning into '/home/ops/verdi/ops/opera-sds-pge'...
Running integration smoke test for container dswx_s1-3.0.0-rc.2.1

================================================
Integration Testing DSWx-S1 PGE docker image...
================================================

Test results output directory: /home/ops/verdi/ops/opera-sds-pge/test_results/dswx_s1
Downloading input data from s3://operasds-dev-pge/dswx_s1/dswx_s1_calval_0.4.2_expected_input.zip to /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_input.zip
download: s3://operasds-dev-pge/dswx_s1/dswx_s1_calval_0.4.2_expected_input.zip to tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_input.zip
Downloading expected outputs from s3://operasds-dev-pge/dswx_s1/dswx_s1_calval_0.4.2_expected_output.zip to /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_output.zip
download: s3://operasds-dev-pge/dswx_s1/dswx_s1_calval_0.4.2_expected_output.zip to tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_output.zip
Extracting test data from /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_input.zip to /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/
Extracting test data from /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_output.zip to /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/
Copying runconfig file /home/ops/verdi/ops/opera-sds-pge/.ci/scripts/dswx_s1/dswx_s1_calval_0.4.2_runconfig.yaml to /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/runconfig/
Input data directory: /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_input/input_dir
Expected data directory: /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_output/expected_output
Creating output directory /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/output_dswx_s1.
Creating scratch directory /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_scratch/scratch_dir.
Running Docker image opera_pge/dswx_s1:3.0.0-rc.2.1 for /data/work/jobs/2024/07/19/01/14/pge_smoke_test__3.0.0-rc.6.0-single_submission-20240718T165322.148697Z/tmp.cuS4bALBqv/dswx_s1_calval_0.4.2_expected_input/input_dir
Running preprocessor for DSWxS1PreProcessorMixin
Starting SAS execution for DSWxS1Executor
Traceback (most recent call last):
  File "/home/dswx_user/opera/scripts/pge_main.py", line 190, in <module>
    pge_main()
  File "/home/dswx_user/opera/scripts/pge_main.py", line 186, in pge_main
    pge_start(run_config_filename)
  File "/home/dswx_user/opera/scripts/pge_main.py", line 160, in pge_start
    pge.run()
  File "/home/dswx_user/opera/pge/base/base_pge.py", line 762, in run
    self.run_postprocessor(**kwargs)
  File "/home/dswx_user/opera/pge/dswx_s1/dswx_s1_pge.py", line 772, in run_postprocessor
    self._run_sas_qa_executable()
  File "/home/dswx_user/opera/pge/base/base_pge.py", line 248, in _run_sas_qa_executable
    elapsed_time = time_and_execute(
                   ^^^^^^^^^^^^^^^^^
  File "/home/dswx_user/opera/util/run_utils.py", line 216, in time_and_execute
    logger.critical(module_name, ErrorCode.SAS_PROGRAM_FAILED, error_msg)
  File "/home/dswx_user/opera/util/logger.py", line 407, in critical
    raise RuntimeError(description)
RuntimeError: Command "['python3', '-m', '/home/dswx_user/opera/.ci/scripts/dswx_s1/compare_dswx_s1_products.sh']" failed with exit code 1, traceback:
/home/dswx_user/miniconda3/envs/DSWX-SAR/bin/python3: Error while finding module specification for '/home/dswx_user/opera/.ci/scripts/dswx_s1/compare_dswx_s1_products.sh' (ModuleNotFoundError: No module named '/home/dswx_user/opera/')

ERROR conda.cli.main_run:execute(124): `conda run sh -c exec ${CONDA_ROOT}/bin/pge_docker_entrypoint.sh  "${@}" -- --file /home/dswx_user/runconfig/dswx_s1_calval_0.4.2_runconfig.yaml` failed. (See above for error)
--no-cleanup flag set: Temporary directories will remain on disk.
Failed to execute integration test for container dswx_s1-3.0.0-rc.2.1
```

### What did you expect?

nt

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by collinss-jpl** [comment]
This is expected to be resolved with integration of `v3.0.0-rc3.0` for DSWx-S1 PGE, which will include the required updates to be run as a smoke test job that are missing from `v3.0.0-r2.1`
