### ISSUE TITLE
[Bug]: DISP-S1 Compressed CSLC retrieval should be tolerance of two identical files

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#991]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

DISP-S1 workflow code incorrectly assumes that there can only be one Compressed CSLC file per burst per acquisition day index. In fact, there can be up to two. Every DISP-S1 frame has up to 6 overlapping bursts at the edges and such bursts are processed in two separate instances of SCIFLO PGE jobs; producing two separate Compressed CSLC files.

https://github.com/nasa/opera-sds-pcm/blob/develop/data_subscriber/cslc_utils.py#L322
The code should expect up to two Compressed CSLCs and just pick the first one

### What did you expect?

n/t

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by philipjyoon** [comment]
```Traceback (most recent call last):
  File "/home/ops/verdi/ops/opera-pcm/util/exec_util.py", line 35, in wrapper
    status = func(*args, **kwargs)
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 56, in main
    run(sys.argv)
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 107, in run
    results["download"] = run_download(args, token, es_conn, netloc, username, password, cmr, job_id)
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/daac_data_subscriber.py", line 156, in run_download
    downloader.run_download(args, token, es_conn, netloc, username, password, cmr, job_id)
  File "/home/ops/verdi/ops/opera-pcm/data_subscriber/asf_cslc_download.py", line 192, in run_download
    raise Exception(f"Failed to get compressed cslc for frame {frame_id} and day index {latest_acq_cycle_index}")
Exception: Failed to get compressed cslc for frame 38239 and day index 216```

**Comment by philipjyoon** [comment]
![image](https://github.com/user-attachments/assets/432d8120-72bd-407b-a0ee-ce10fcfe5246)

**Comment by philipjyoon** [comment]
Opening this ticket again. We learned recently that there will be cases where the duplicate c-cslcs may not be identical. Therefore we need to select the one that belongs to that specific frame being processed.
